/**
 * Design-loop fixtures for the Locations & Departments workspace preview.
 *
 * `/app/locations` needs a real Supabase session and a seeded organisation, so
 * `/locations-preview` renders the same components against these fixed rows.
 * The numbers reproduce design/Locations-Management.png and
 * design/Location-department.png exactly. Do not "improve" them. Nothing here
 * is used by the authenticated routes.
 */

import type {
  DepartmentDetails,
  DepartmentRow,
  LocationDetails,
  LocationRow,
  SiteStat,
} from '@/lib/locationsDirectory';

export const DEMO_LOCATION_STATS: SiteStat[] = [
  {
    id: 'total',
    label: 'Total Locations',
    value: '12',
    hint: 'Active sites',
    icon: 'pin',
    tone: 'primary',
  },
  {
    id: 'active',
    label: 'Active Locations',
    value: '10',
    hint: 'Online & operational',
    icon: 'check',
    tone: 'success',
  },
  {
    id: 'staff',
    label: 'Total Staff Assigned',
    value: '238',
    hint: 'Across all locations',
    icon: 'staff',
    tone: 'violet',
  },
  {
    id: 'shifts',
    label: 'Upcoming Shifts (7 days)',
    value: '312',
    hint: 'Across all locations',
    icon: 'calendar',
    tone: 'warning',
  },
  {
    id: 'coverage',
    label: 'Avg. Coverage',
    value: '92%',
    hint: 'Target: 90%',
    icon: 'coverage',
    tone: 'success',
  },
];

export const DEMO_LOCATIONS: LocationRow[] = [
  {
    id: 'sunnyvale-care-home',
    name: 'Sunnyvale Care Home',
    address: '12 Park Road, Sunnyvale, SV1 2AB',
    photoUrl: null,
    type: 'Care Home',
    typeTone: 'violet',
    region: 'South West',
    staff: 52,
    upcomingShifts: 68,
    coveragePercent: 95,
    status: 'active',
  },
  {
    id: 'riverside-house',
    name: 'Riverside House',
    address: '45 Mill Lane, Sunnyvale, SV1 3PT',
    photoUrl: null,
    type: 'Care Home',
    typeTone: 'violet',
    region: 'South West',
    staff: 46,
    upcomingShifts: 62,
    coveragePercent: 91,
    status: 'active',
  },
  {
    id: 'oakview-day-centre',
    name: 'Oakview Day Centre',
    address: '7 Oak Street, Sunnyvale, SV1 1PL',
    photoUrl: null,
    type: 'Day Centre',
    typeTone: 'info',
    region: 'South West',
    staff: 28,
    upcomingShifts: 34,
    coveragePercent: 88,
    status: 'active',
  },
  {
    id: 'greenfield-domiciliary',
    name: 'Greenfield Domiciliary',
    address: 'Unit 3, Greenfield Way, SV1 4QA',
    photoUrl: null,
    type: 'Domiciliary',
    typeTone: 'success',
    region: 'South West',
    staff: 64,
    upcomingShifts: 96,
    coveragePercent: 93,
    status: 'active',
  },
  {
    id: 'westview-care-home',
    name: 'Westview Care Home',
    address: '89 West Road, Sunnyvale, SV1 2XL',
    photoUrl: null,
    type: 'Care Home',
    typeTone: 'violet',
    region: 'South West',
    staff: 40,
    upcomingShifts: 44,
    coveragePercent: 85,
    status: 'maintenance',
  },
  {
    id: 'meadowbank-hospice',
    name: 'Meadowbank Hospice',
    address: '12 Meadowbank Drive, SV1 6TR',
    photoUrl: null,
    type: 'Hospice',
    typeTone: 'rose',
    region: 'South West',
    staff: 25,
    upcomingShifts: 28,
    coveragePercent: 90,
    status: 'active',
  },
  {
    id: 'highlands-supported-living',
    name: 'Highlands Supported Living',
    address: '3 Highlands Court, SV1 5QD',
    photoUrl: null,
    type: 'Supported Living',
    typeTone: 'warning',
    region: 'South West',
    staff: 30,
    upcomingShifts: 36,
    coveragePercent: 87,
    status: 'active',
  },
  {
    id: 'seaview-community-hub',
    name: 'Seaview Community Hub',
    address: '21 Seaview Parade, SV1 1QZ',
    photoUrl: null,
    type: 'Community Hub',
    typeTone: 'teal',
    region: 'South West',
    staff: 16,
    upcomingShifts: 18,
    coveragePercent: 78,
    status: 'inactive',
  },
];

/** The reference's pager reads "1 to 8 of 12", so four rows sit on page 2. */
export const DEMO_LOCATION_TOTAL = 12;

export const DEMO_LOCATION_DETAILS: LocationDetails = {
  id: 'sunnyvale-care-home',
  name: 'Sunnyvale Care Home',
  status: 'active',
  photoUrl: null,
  addressLines: ['12 Park Road', 'Sunnyvale, SV1 2AB', 'South West'],
  phone: '020 7946 0958',
  email: 'sunnyvale@scgroup.uk',
  metrics: [
    {
      id: 'staff',
      label: 'Staff Assigned',
      value: '52',
      hint: 'View staff',
      hintTone: 'link',
    },
    { id: 'shifts', label: 'Upcoming Shifts', value: '68', hint: 'Next 7 days' },
    { id: 'coverage', label: 'Coverage', value: '95%', hint: 'Target: 90%' },
    { id: 'type', label: 'Location Type', value: 'Care Home' },
    { id: 'capacity', label: 'Capacity', value: '60 residents' },
    { id: 'hours', label: 'Open Hours', value: '24/7' },
  ],
  info: [
    {
      id: 'manager',
      label: 'Manager',
      value: 'Sarah Johnson',
      avatarName: 'Sarah Johnson',
    },
    { id: 'timezone', label: 'Time Zone', value: '(GMT+1) London' },
    { id: 'payroll', label: 'Payroll Location Code', value: 'SVCH01' },
    { id: 'cost-centre', label: 'Cost Centre', value: 'CC-1001' },
    { id: 'notes', label: 'Notes', value: 'Primary residential care home.' },
  ],
  activity: [
    {
      id: 'settings',
      kind: 'complete',
      title: 'Location settings updated',
      detail: 'By James Davis',
      timeLabel: 'Today, 09:45',
    },
    {
      id: 'staff',
      kind: 'staff',
      title: 'New staff assigned',
      detail: '5 staff members',
      timeLabel: 'Yesterday, 16:20',
    },
    {
      id: 'maintenance',
      kind: 'maintenance',
      title: 'Maintenance scheduled',
      detail: 'Boiler service',
      timeLabel: '20 May 2025',
    },
  ],
};

export const DEMO_DEPARTMENT_STATS: SiteStat[] = [
  {
    id: 'total',
    label: 'Total Departments',
    value: '14',
    hint: 'Across all locations',
    icon: 'pin',
    tone: 'primary',
  },
  {
    id: 'staff',
    label: 'Total Staff',
    value: '238',
    hint: 'Assigned to departments',
    icon: 'staff',
    tone: 'success',
  },
  {
    id: 'shifts',
    label: 'Upcoming Shifts (7 days)',
    value: '312',
    hint: 'In department schedules',
    icon: 'calendar',
    tone: 'warning',
  },
  {
    id: 'coverage',
    label: 'Avg. Coverage',
    value: '92%',
    hint: 'Target: 90%',
    icon: 'coverage',
    tone: 'violet',
  },
];

export const DEMO_DEPARTMENTS: DepartmentRow[] = [
  {
    id: 'nursing',
    name: 'Nursing',
    description: 'Patient care and clinical services',
    icon: 'clinical',
    iconTone: 'rose',
    location: 'Sunnyvale Care Home',
    type: 'Clinical',
    typeTone: 'rose',
    staff: 56,
    upcomingShifts: 72,
    coveragePercent: 96,
    status: 'active',
  },
  {
    id: 'care-assistants',
    name: 'Care Assistants',
    description: 'Direct care and support',
    icon: 'care',
    iconTone: 'primary',
    location: 'All Locations',
    type: 'Clinical',
    typeTone: 'rose',
    staff: 84,
    upcomingShifts: 112,
    coveragePercent: 93,
    status: 'active',
  },
  {
    id: 'night-care',
    name: 'Night Care',
    description: 'Overnight care and supervision',
    icon: 'night',
    iconTone: 'violet',
    location: 'Sunnyvale Care Home',
    type: 'Clinical',
    typeTone: 'rose',
    staff: 28,
    upcomingShifts: 34,
    coveragePercent: 89,
    status: 'active',
  },
  {
    id: 'therapy-services',
    name: 'Therapy Services',
    description: 'Rehabilitation and therapy',
    icon: 'therapy',
    iconTone: 'teal',
    location: 'Oakview Day Centre',
    type: 'Allied Health',
    typeTone: 'success',
    staff: 18,
    upcomingShifts: 24,
    coveragePercent: 94,
    status: 'active',
  },
  {
    id: 'housekeeping',
    name: 'Housekeeping',
    description: 'Cleaning and linen services',
    icon: 'housekeeping',
    iconTone: 'warning',
    location: 'All Locations',
    type: 'Support',
    typeTone: 'warning',
    staff: 22,
    upcomingShifts: 28,
    coveragePercent: 92,
    status: 'active',
  },
  {
    id: 'catering',
    name: 'Catering',
    description: 'Food services and nutrition',
    icon: 'catering',
    iconTone: 'violet',
    location: 'All Locations',
    type: 'Support',
    typeTone: 'warning',
    staff: 16,
    upcomingShifts: 20,
    coveragePercent: 90,
    status: 'active',
  },
  {
    id: 'maintenance',
    name: 'Maintenance',
    description: 'Building and equipment',
    icon: 'maintenance',
    iconTone: 'info',
    location: 'Meadowbank Hospice',
    type: 'Support',
    typeTone: 'warning',
    staff: 12,
    upcomingShifts: 16,
    coveragePercent: 88,
    status: 'active',
  },
  {
    id: 'administration',
    name: 'Administration',
    description: 'Office and administrative',
    icon: 'admin',
    iconTone: 'success',
    location: 'All Locations',
    type: 'Corporate',
    typeTone: 'info',
    staff: 14,
    upcomingShifts: 18,
    coveragePercent: 95,
    status: 'active',
  },
];

/** The reference's pager reads "1 to 8 of 14". */
export const DEMO_DEPARTMENT_TOTAL = 14;

export const DEMO_DEPARTMENT_DETAILS: DepartmentDetails = {
  id: 'nursing',
  name: 'Nursing',
  status: 'active',
  icon: 'clinical',
  iconTone: 'rose',
  type: 'Clinical Department',
  typeTone: 'rose',
  description:
    'Responsible for all aspects of patient care and clinical management across the organisation.',
  metrics: [
    {
      id: 'staff',
      label: 'Staff Assigned',
      value: '56',
      hint: 'View staff',
      hintTone: 'link',
    },
    { id: 'shifts', label: 'Upcoming Shifts', value: '72', hint: 'Next 7 days' },
    { id: 'coverage', label: 'Coverage', value: '96%', hint: 'Target: 90%' },
    {
      id: 'locations',
      label: 'Locations',
      value: '2',
      hint: 'View locations',
      hintTone: 'link',
    },
    { id: 'open', label: 'Open Shifts', value: '3', hint: 'Needs cover' },
    { id: 'budget', label: 'Budget Used', value: '87%', hint: 'This month' },
  ],
  activity: [
    {
      id: 'template',
      kind: 'complete',
      title: 'Shift template updated',
      detail: 'By Sarah Johnson',
      timeLabel: 'Today, 09:15',
    },
    {
      id: 'staff',
      kind: 'staff',
      title: 'New staff assigned',
      detail: '3 staff members',
      timeLabel: 'Yesterday, 16:20',
    },
    {
      id: 'settings',
      kind: 'settings',
      title: 'Department settings updated',
      detail: 'By James Davis',
      timeLabel: '20 May 2026',
    },
    {
      id: 'qualification',
      kind: 'qualification',
      title: 'New qualification added',
      detail: 'Basic Life Support',
      timeLabel: '18 May 2026',
    },
  ],
};
