import {
  BarChart3,
  Building2,
  CalendarDays,
  Clock3,
  PoundSterling,
  Repeat2,
  ShieldCheck,
  UserRound,
  Users,
} from 'lucide-react';
import type { ReportRow } from '@/lib/reportRows';
import type { RecentReport } from '@/components/reports/RecentReportsCard';
import type { ReportsOverviewSegment } from '@/components/reports/ReportsOverviewCard';

/**
 * Fixtures for `/reports-preview` — the exact catalogue, run times, cadences
 * and overview split shown in design/Reports-Dashboard.png. Design-loop only:
 * `/app/reports` builds its rows from the real catalogue and this browser's
 * run log. See design/.loop/reports-log.md.
 */

const RUN_BY = 'James Davis';

export const DEMO_REPORTS: ReportRow[] = [
  {
    id: 'scheduled-rota',
    name: 'Scheduled Rota Report',
    category: 'Scheduling',
    description: 'Full rota for selected date range and locations.',
    icon: CalendarDays,
    lastRunLabel: 'Today, 09:15',
    lastRunBy: RUN_BY,
    frequency: 'Weekly',
    format: 'PDF',
    favourite: true,
    runnable: true,
  },
  {
    id: 'staff-availability',
    name: 'Staff Availability Report',
    category: 'Staffing',
    description: 'Availability and preferences summary.',
    icon: Users,
    lastRunLabel: 'Yesterday, 16:30',
    lastRunBy: RUN_BY,
    frequency: 'Weekly',
    format: 'Excel',
    favourite: false,
    runnable: true,
  },
  {
    id: 'timesheet-summary',
    name: 'Timesheet Summary',
    category: 'Timesheets',
    description: 'Worked hours, overtime and totals.',
    icon: Clock3,
    lastRunLabel: 'Today, 08:45',
    lastRunBy: RUN_BY,
    frequency: 'Weekly',
    format: 'Excel',
    favourite: true,
    runnable: true,
  },
  {
    id: 'labour-cost',
    name: 'Labour Cost Report',
    category: 'Finance',
    description: 'Labour cost by location and department.',
    icon: PoundSterling,
    lastRunLabel: 'Yesterday, 12:10',
    lastRunBy: RUN_BY,
    frequency: 'Weekly',
    format: 'Excel',
    favourite: false,
    runnable: true,
  },
  {
    id: 'leave-summary',
    name: 'Leave Summary Report',
    category: 'Leave',
    description: 'Leave balances and leave taken.',
    icon: ShieldCheck,
    lastRunLabel: '24 May 2025',
    lastRunBy: RUN_BY,
    frequency: 'Monthly',
    format: 'PDF',
    favourite: false,
    runnable: true,
  },
  {
    id: 'swap-activity',
    name: 'Swap Activity Report',
    category: 'Swaps',
    description: 'All shift swaps and outcomes.',
    icon: Repeat2,
    lastRunLabel: '24 May 2025',
    lastRunBy: RUN_BY,
    frequency: 'Monthly',
    format: 'Excel',
    favourite: false,
    runnable: true,
  },
  {
    id: 'overtime-analysis',
    name: 'Overtime Analysis',
    category: 'Analytics',
    description: 'Overtime trends and costs.',
    icon: BarChart3,
    lastRunLabel: '23 May 2025',
    lastRunBy: RUN_BY,
    frequency: 'Monthly',
    format: 'Excel',
    favourite: false,
    runnable: true,
  },
  {
    id: 'compliance',
    name: 'Compliance Report',
    category: 'Compliance',
    description: 'Mandatory training and document expiry.',
    icon: ShieldCheck,
    lastRunLabel: '22 May 2025',
    lastRunBy: RUN_BY,
    frequency: 'Monthly',
    format: 'PDF',
    favourite: false,
    runnable: true,
  },
  {
    id: 'location-summary',
    name: 'Location Summary',
    category: 'Operations',
    description: 'Coverage and staffing by location.',
    icon: Building2,
    lastRunLabel: '22 May 2025',
    lastRunBy: RUN_BY,
    frequency: 'Monthly',
    format: 'PDF',
    favourite: false,
    runnable: true,
  },
  {
    id: 'new-starters',
    name: 'New Starters Report',
    category: 'HR',
    description: 'New starters within selected period.',
    icon: UserRound,
    lastRunLabel: '21 May 2025',
    lastRunBy: RUN_BY,
    frequency: 'Monthly',
    format: 'Excel',
    favourite: false,
    runnable: true,
  },
];

export const DEMO_OVERVIEW: ReportsOverviewSegment[] = [
  {
    id: 'generated',
    label: 'Generated',
    value: 16,
    percent: 57,
    strokeClass: 'stroke-success',
    dotClass: 'bg-success',
  },
  {
    id: 'scheduled',
    label: 'Scheduled',
    value: 7,
    percent: 25,
    strokeClass: 'stroke-primary',
    dotClass: 'bg-primary',
  },
  {
    id: 'saved',
    label: 'Saved',
    value: 3,
    percent: 11,
    strokeClass: 'stroke-warning',
    dotClass: 'bg-warning',
  },
  {
    id: 'failed',
    label: 'Failed',
    value: 2,
    percent: 7,
    strokeClass: 'stroke-danger',
    dotClass: 'bg-danger',
  },
];

export const DEMO_RECENT_REPORTS: RecentReport[] = [
  {
    id: 'recent-rota',
    name: 'Scheduled Rota Report',
    icon: CalendarDays,
    category: 'Scheduling',
    scope: 'Sunnyvale Care Home',
    runLabel: 'Today, 09:15',
    format: 'PDF',
  },
  {
    id: 'recent-timesheet',
    name: 'Timesheet Summary',
    icon: Clock3,
    category: 'Compliance',
    scope: 'All Locations',
    runLabel: 'Today, 08:45',
    format: 'Excel',
  },
  {
    id: 'recent-labour',
    name: 'Labour Cost Report',
    icon: PoundSterling,
    category: 'Finance',
    scope: 'All Locations',
    runLabel: 'Yesterday, 12:10',
    format: 'Excel',
  },
  {
    id: 'recent-leave',
    name: 'Leave Summary Report',
    icon: ShieldCheck,
    category: 'Leave',
    scope: 'All Locations',
    runLabel: '24 May 2025',
    format: 'PDF',
  },
];
