/**
 * Design-loop fixtures for the Staff Directory and Staff Profile previews.
 *
 * `/app/staff` needs a real Supabase session and a seeded organisation, so the
 * `/staff-preview` routes render the same components against these fixed rows.
 * The numbers reproduce design/staff.png and design/Staff-Profile.png exactly —
 * do not "improve" them. Nothing here is used by the authenticated routes.
 */

import type {
  StaffDetails,
  StaffDirectoryRow,
  StaffDirectoryStats,
} from '@/lib/staffDirectory';
import type { StaffProfileData } from '@/lib/staffProfile';

export const DEMO_STATS: StaffDirectoryStats = {
  totalStaff: 42,
  onShiftToday: 22,
  onLeaveToday: 6,
  unavailableToday: 4,
  vacancies: 8,
};

export const DEMO_STAFF: StaffDirectoryRow[] = [
  {
    id: 'sarah-johnson',
    firstName: 'Sarah',
    lastName: 'Johnson',
    photoUrl: null,
    payrollId: 'RN12345',
    role: 'Senior Nurse',
    roleCode: 'RN',
    roleCodeTone: 'violet',
    department: 'Nursing',
    location: 'Sunshine Care Home',
    skills: ['Nursing', 'Medication', 'Care Plan', 'Dementia Care', 'Safeguarding'],
    availability: [
      'available',
      'available',
      'available',
      'available',
      'available',
      'none',
    ],
    availabilityPercent: 100,
    status: 'active',
  },
  {
    id: 'michael-brown',
    firstName: 'Michael',
    lastName: 'Brown',
    photoUrl: null,
    payrollId: 'CA98765',
    role: 'Care Assistant',
    roleCode: 'CA',
    roleCodeTone: 'neutral',
    department: 'Care',
    location: 'Sunshine Care Home',
    skills: ['Personal Care', 'Moving & Handling', 'Dementia Care'],
    availability: ['available', 'available', 'available', 'available', 'none', 'none'],
    availabilityPercent: 80,
    status: 'active',
  },
  {
    id: 'emily-davis',
    firstName: 'Emily',
    lastName: 'Davis',
    photoUrl: null,
    payrollId: 'CA11223',
    role: 'Care Assistant',
    roleCode: 'CA',
    roleCodeTone: 'neutral',
    department: 'Care',
    location: 'Riverside House',
    skills: ['Personal Care', 'Dementia Care'],
    availability: [
      'available',
      'available',
      'available',
      'available',
      'available',
      'none',
    ],
    availabilityPercent: 100,
    status: 'active',
  },
  {
    id: 'daniel-lee',
    firstName: 'Daniel',
    lastName: 'Lee',
    photoUrl: null,
    payrollId: 'CA33445',
    role: 'Care Assistant',
    roleCode: 'CA',
    roleCodeTone: 'neutral',
    department: 'Care',
    location: 'Riverside House',
    skills: ['Personal Care'],
    availability: ['available', 'available', 'partial', 'partial', 'partial', 'none'],
    availabilityPercent: 60,
    status: 'active',
  },
  {
    id: 'aisha-patel',
    firstName: 'Aisha',
    lastName: 'Patel',
    photoUrl: null,
    payrollId: 'RN55667',
    role: 'Senior Nurse',
    roleCode: 'RN',
    roleCodeTone: 'violet',
    department: 'Nursing',
    location: 'Oakview Care Home',
    skills: ['Nursing', 'Wound Care', 'Medication', 'Care Plan'],
    availability: [
      'available',
      'available',
      'available',
      'available',
      'available',
      'none',
    ],
    availabilityPercent: 100,
    status: 'active',
  },
  {
    id: 'james-wilson',
    firstName: 'James',
    lastName: 'Wilson',
    photoUrl: null,
    payrollId: 'CA77889',
    role: 'Care Assistant',
    roleCode: 'CA',
    roleCodeTone: 'neutral',
    department: 'Care',
    location: 'Oakview Care Home',
    skills: ['Personal Care', 'Moving & Handling'],
    availability: ['available', 'partial', 'none', 'partial', 'partial', 'none'],
    availabilityPercent: 60,
    status: 'active',
  },
  {
    id: 'grace-thompson',
    firstName: 'Grace',
    lastName: 'Thompson',
    photoUrl: null,
    payrollId: 'RN99001',
    role: 'Senior Nurse',
    roleCode: 'RN',
    roleCodeTone: 'violet',
    department: 'Nursing',
    location: 'Sunshine Care Home',
    skills: ['Nursing', 'Leadership', 'Medication'],
    availability: [
      'available',
      'available',
      'available',
      'available',
      'available',
      'none',
    ],
    availabilityPercent: 100,
    status: 'active',
  },
  {
    id: 'liam-oconnor',
    firstName: 'Liam',
    lastName: "O'Connor",
    photoUrl: null,
    payrollId: 'CA22334',
    role: 'Care Assistant',
    roleCode: 'CA',
    roleCodeTone: 'neutral',
    department: 'Care',
    location: 'Riverside House',
    skills: ['Personal Care'],
    availability: ['unavailable', 'unavailable', 'unavailable', 'none', 'none', 'none'],
    availabilityPercent: 40,
    status: 'on_leave',
  },
];

export const DEMO_STAFF_DETAILS: StaffDetails = {
  id: 'sarah-johnson',
  firstName: 'Sarah',
  lastName: 'Johnson',
  photoUrl: null,
  role: 'Senior Nurse',
  location: 'Sunshine Care Home',
  email: 'sarah.johnson@sunnyvale.co.uk',
  phone: '07712 345 678',
  joinedLabel: 'Joined 12 March 2022',
  status: 'active',
  skills: ['Nursing', 'Medication', 'Care Plan', 'Dementia Care', 'Safeguarding'],
  week: [
    { weekday: 'Mon', date: '26 May', timeLabel: '07:00 – 15:00', tone: 'default' },
    { weekday: 'Tue', date: '27 May', timeLabel: '07:00 – 15:00', tone: 'default' },
    { weekday: 'Wed', date: '28 May', timeLabel: '15:00 – 23:00', tone: 'accent' },
    { weekday: 'Thu', date: '29 May', timeLabel: '07:00 – 15:00', tone: 'default' },
    { weekday: 'Fri', date: '30 May', timeLabel: '07:00 – 15:00', tone: 'default' },
    { weekday: 'Sat', date: '31 May', timeLabel: null, tone: 'off' },
    { weekday: 'Sun', date: '1 Jun', timeLabel: null, tone: 'off' },
  ],
  documents: [
    {
      id: 'doc-nmc',
      name: 'NMC Pin Certificate',
      expiresLabel: 'Expires 31 Dec 2025',
      status: 'valid',
    },
    {
      id: 'doc-bls',
      name: 'Basic Life Support',
      expiresLabel: 'Expires 14 Jul 2025',
      status: 'expiring',
    },
    {
      id: 'doc-mh',
      name: 'Moving & Handling',
      expiresLabel: 'Expires 10 Sep 2025',
      status: 'valid',
    },
  ],
};

export const DEMO_PROFILE: StaffProfileData = {
  id: 'sarah-johnson',
  firstName: 'Sarah',
  lastName: 'Johnson',
  photoUrl: null,
  role: 'Senior Nurse',
  department: 'Nursing',
  location: 'Sunshine Care Home',
  active: true,
  personal: {
    email: 'sarah.johnson@sunnyvale.co.uk',
    phone: '07712 345 678',
    joinedLabel: 'Joined 12 March 2022',
    birthLabel: '12 July 1991 (33 years old)',
    gender: 'Female',
    location: 'London, United Kingdom',
  },
  work: [
    { label: 'Employee ID', value: 'RN12345' },
    {
      label: 'Role',
      value: 'Senior Nurse',
      badge: { code: 'RN', tone: 'violet' },
    },
    { label: 'Department', value: 'Nursing' },
    { label: 'Location', value: 'Sunshine Care Home' },
    { label: 'Employment Type', value: 'Full-time' },
    { label: 'Contracted Hours', value: '37.5 hours / week' },
    { label: 'Pay Rate', value: '£18.75 / hour' },
    { label: 'Line Manager', value: 'James Davis' },
    { label: 'Probation End Date', value: '12 March 2023' },
  ],
  metrics: [
    { label: 'Shifts This Month', value: '16', hint: '128.00 hours' },
    { label: 'Hours This Month', value: '128.00', hint: '85% of contracted' },
    { label: 'Upcoming Shifts', value: '4', hint: 'Next: Today 07:00' },
    { label: 'Leave Balance', value: '18.5', hint: 'days remaining' },
    { label: 'Shift Rating', value: '4.8', suffix: '/ 5', hint: 'From 24 reviews' },
  ],
  upcoming: [
    {
      id: 'shift-27',
      dateLabel: 'Today, 27 May',
      timeLabel: '07:00 – 15:00',
      typeName: 'Morning Shift',
      typeTone: 'morning',
      locationName: 'Sunshine Care Home',
      areaName: 'Nursing Floor 1',
      confirmed: true,
    },
    {
      id: 'shift-29',
      dateLabel: 'Thu, 29 May',
      timeLabel: '07:00 – 15:00',
      typeName: 'Morning Shift',
      typeTone: 'morning',
      locationName: 'Sunshine Care Home',
      areaName: 'Nursing Floor 1',
      confirmed: true,
    },
    {
      id: 'shift-30',
      dateLabel: 'Fri, 30 May',
      timeLabel: '07:00 – 15:00',
      typeName: 'Morning Shift',
      typeTone: 'morning',
      locationName: 'Sunshine Care Home',
      areaName: 'Nursing Floor 1',
      confirmed: true,
    },
    {
      id: 'shift-01',
      dateLabel: 'Sun, 1 June',
      timeLabel: '15:00 – 23:00',
      typeName: 'Evening Shift',
      typeTone: 'evening',
      locationName: 'Sunshine Care Home',
      areaName: 'Nursing Floor 2',
      confirmed: true,
    },
  ],
  summaryMonth: 'May 2025',
  summary: [
    { label: 'Total Shifts', value: '16', tone: 'total' },
    { label: 'Morning', value: '10', tone: 'morning' },
    { label: 'Evening', value: '4', tone: 'evening' },
    { label: 'Night', value: '2', tone: 'night' },
    { label: 'Hours Worked', value: '128.00', tone: null },
  ],
  summaryHint: '85% of contracted',
  activity: [
    {
      id: 'act-1',
      kind: 'shift',
      title: 'Shift confirmed',
      detail: 'Sunshine Care Home • 27 May 2025',
      timeLabel: 'Today, 09:15',
    },
    {
      id: 'act-2',
      kind: 'swap',
      title: 'Swap approved',
      detail: 'With Michael Brown • 22 May 2025',
      timeLabel: '22 May, 16:30',
    },
    {
      id: 'act-3',
      kind: 'leave',
      title: 'Leave request approved',
      detail: 'Annual Leave • 18–22 Aug 2025',
      timeLabel: '20 May, 11:02',
    },
    {
      id: 'act-4',
      kind: 'document',
      title: 'Document uploaded',
      detail: 'NMC Pin Certificate',
      timeLabel: '19 May, 14:45',
    },
  ],
  skills: [
    { name: 'Nursing', level: 'Advanced' },
    { name: 'Medication Administration', level: 'Advanced' },
    { name: 'Dementia Care', level: 'Advanced' },
    { name: 'Wound Care', level: 'Intermediate' },
    { name: 'Moving & Handling', level: 'Advanced' },
    { name: 'Safeguarding', level: 'Advanced' },
  ],
  qualifications: [
    {
      id: 'qual-rn',
      name: 'Registered Nurse (RN)',
      issuer: 'NMC',
      status: 'Active',
      icon: 'award',
    },
    {
      id: 'qual-bsc',
      name: 'BSc Nursing',
      issuer: 'University of Manchester',
      status: 'Completed',
      icon: 'award',
    },
    {
      id: 'qual-bls',
      name: 'Basic Life Support',
      issuer: 'Resuscitation Council UK',
      status: null,
      validLabel: 'Valid until 12 Dec 2025',
      icon: 'file',
    },
  ],
  moreQualifications: 2,
  documents: [
    {
      id: 'pdoc-nmc',
      name: 'NMC Pin Certificate',
      expiresLabel: 'Expires 31 Dec 2025',
      status: 'valid',
    },
    {
      id: 'pdoc-dbs',
      name: 'DBS Certificate',
      expiresLabel: 'Expires 4 Mar 2026',
      status: 'valid',
    },
    {
      id: 'pdoc-flu',
      name: 'Flu Vaccination',
      expiresLabel: 'Expires 15 Nov 2025',
      status: 'expiring',
    },
    {
      id: 'pdoc-mh',
      name: 'Moving & Handling',
      expiresLabel: 'Expires 10 Sep 2025',
      status: 'valid',
    },
  ],
};
