-- =====================================================================
-- 0021 — Platform incidents
--
-- The console has shown an incident register since the platform screens were
-- built, and every row of it was invented. This is the table behind it.
--
-- ## Why an incident is not an audit row
--
-- `audit_logs` answers "who did what". An incident answers "what was broken,
-- for whom, for how long, and what did we tell people". Those have different
-- lifetimes — an audit row is written once and never changes, an incident is
-- edited repeatedly while it is open — and different audiences. Forcing one
-- into the other would make the audit log mutable, which is the single
-- property it exists to guarantee.
--
-- ## Who may read it
--
-- Platform staff, and nobody else, for now. A public status page is a second
-- surface with its own hosting and its own audience, and `is_public` is here
-- so that decision can be made later without a migration — but no policy
-- grants anon access today, so setting it changes nothing until one does.
-- =====================================================================

create table if not exists public.incidents (
  id            uuid primary key default gen_random_uuid(),

  -- Human reference, the thing people say out loud: "INC-0142". Generated by
  -- the declare function from a sequence so two administrators declaring at
  -- the same moment cannot land on the same number.
  reference     text not null unique,

  title         text not null check (length(btrim(title)) > 0),

  -- Blast radius in one sentence: who was affected and for how long. Required,
  -- because an incident nobody described is one nobody can learn from.
  impact        text not null check (length(btrim(impact)) > 0),

  severity      text not null check (severity in ('critical','high','medium','low')),

  status        text not null default 'investigating'
                  check (status in ('investigating','identified','monitoring','resolved')),

  -- Free text rather than a foreign key: the affected service may be one this
  -- deployment does not own (an OAuth provider, an APNs endpoint), and a
  -- lookup table would refuse exactly the incidents worth recording.
  service       text not null,

  started_at    timestamptz not null default timezone('utc', now()),
  detected_at   timestamptz,
  resolved_at   timestamptz,

  owner_id      uuid references public.profiles(id) on delete set null,

  -- Published when resolved. The thing a customer reads.
  resolution    text,

  -- Reserved for a public status page. No policy grants anon access, so this
  -- is a stored intent rather than a live switch.
  is_public     boolean not null default false,

  created_at    timestamptz not null default timezone('utc', now()),
  updated_at    timestamptz not null default timezone('utc', now()),

  constraint incidents_resolved_after_start
    check (resolved_at is null or resolved_at >= started_at),
  constraint incidents_detected_after_start
    check (detected_at is null or detected_at >= started_at),
  -- A resolved incident has both a time and a resolution note. Mean time to
  -- resolve is computed from this column, and a resolved row without one is a
  -- silent hole in the average.
  constraint incidents_resolved_is_complete
    check (status <> 'resolved'
           or (resolved_at is not null and nullif(btrim(coalesce(resolution,'')),'') is not null))
);

comment on table public.incidents is
  'Platform incidents: what broke, how bad, who owned it, and when it was resolved. Platform staff only.';

create sequence if not exists public.incident_reference_seq start with 138;

create index if not exists incidents_open_idx
  on public.incidents (started_at desc)
  where status <> 'resolved';

create index if not exists incidents_started_idx
  on public.incidents (started_at desc);

-- ---------- The timeline ------------------------------------------------
-- Separate rows rather than an appended text column: "what did we know at
-- 09:20" is the question a post-incident review opens with, and a single
-- edited field cannot answer it.
create table if not exists public.incident_updates (
  id           uuid primary key default gen_random_uuid(),
  incident_id  uuid not null references public.incidents(id) on delete cascade,
  author_id    uuid references public.profiles(id) on delete set null,
  status       text not null
                 check (status in ('investigating','identified','monitoring','resolved')),
  body         text not null check (length(btrim(body)) > 0),
  created_at   timestamptz not null default timezone('utc', now())
);

comment on table public.incident_updates is
  'Timeline of one incident. Append-only in practice: entries are what was believed at the time.';

create index if not exists incident_updates_incident_idx
  on public.incident_updates (incident_id, created_at);

drop trigger if exists incidents_set_updated_at on public.incidents;
create trigger incidents_set_updated_at
  before update on public.incidents
  for each row execute function public.set_updated_at();

-- ---------- Declare -----------------------------------------------------
create or replace function public.declare_incident(
  p_title    text,
  p_impact   text,
  p_severity text,
  p_service  text,
  p_started_at timestamptz default null
) returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_id  uuid;
  v_ref text;
begin
  if not public.has_platform_role(
       array['platform_owner','platform_admin','platform_support']) then
    raise exception 'Only platform staff can declare an incident'
      using errcode = '42501';
  end if;

  v_ref := 'INC-' || lpad(nextval('public.incident_reference_seq')::text, 4, '0');

  insert into public.incidents
    (reference, title, impact, severity, service, started_at, detected_at, owner_id)
  values
    (v_ref, btrim(p_title), btrim(p_impact), p_severity, btrim(p_service),
     coalesce(p_started_at, timezone('utc', now())), timezone('utc', now()), auth.uid())
  returning id into v_id;

  insert into public.incident_updates (incident_id, author_id, status, body)
  values (v_id, auth.uid(), 'investigating', btrim(p_impact));

  perform public.audit_write(
    null, 'incident.declared', 'incident', v_id,
    jsonb_build_object('reference', v_ref, 'severity', p_severity, 'service', p_service,
                       'after', p_severity),
    case when p_severity = 'critical' then 'critical' else 'warning' end,
    'platform_only');

  return v_id;
end;
$$;

revoke all on function public.declare_incident(text, text, text, text, timestamptz)
  from public, anon;
grant execute on function public.declare_incident(text, text, text, text, timestamptz)
  to authenticated;

-- ---------- Move it along ----------------------------------------------
create or replace function public.add_incident_update(
  p_incident uuid,
  p_status   text,
  p_body     text
) returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_update uuid;
  r public.incidents;
begin
  if not public.has_platform_role(
       array['platform_owner','platform_admin','platform_support']) then
    raise exception 'Only platform staff can update an incident'
      using errcode = '42501';
  end if;

  select * into r from public.incidents where id = p_incident;
  if not found then
    raise exception 'Incident not found' using errcode = 'P0002';
  end if;

  -- Resolving is its own function, because it needs a resolution note and a
  -- time. Allowing it here would let a timeline entry close an incident
  -- without either.
  if p_status = 'resolved' then
    raise exception 'Use resolve_incident to close an incident'
      using errcode = '22023';
  end if;

  insert into public.incident_updates (incident_id, author_id, status, body)
  values (p_incident, auth.uid(), p_status, btrim(p_body))
  returning id into v_update;

  update public.incidents set status = p_status where id = p_incident;

  perform public.audit_write(
    null, 'incident.updated', 'incident', p_incident,
    jsonb_build_object('reference', r.reference, 'before', r.status, 'after', p_status),
    'notice', 'platform_only');

  return v_update;
end;
$$;

revoke all on function public.add_incident_update(uuid, text, text) from public, anon;
grant execute on function public.add_incident_update(uuid, text, text) to authenticated;

-- ---------- Resolve -----------------------------------------------------
create or replace function public.resolve_incident(
  p_incident   uuid,
  p_resolution text
) returns void language plpgsql security definer set search_path = public as $$
declare
  r public.incidents;
begin
  if not public.has_platform_role(
       array['platform_owner','platform_admin','platform_support']) then
    raise exception 'Only platform staff can resolve an incident'
      using errcode = '42501';
  end if;

  if nullif(btrim(coalesce(p_resolution, '')), '') is null then
    raise exception 'Resolving an incident needs a resolution note'
      using errcode = '23514';
  end if;

  select * into r from public.incidents where id = p_incident;
  if not found then
    raise exception 'Incident not found' using errcode = 'P0002';
  end if;
  if r.status = 'resolved' then
    raise exception 'Incident % is already resolved', r.reference using errcode = '22023';
  end if;

  update public.incidents
     set status      = 'resolved',
         resolved_at = timezone('utc', now()),
         resolution  = btrim(p_resolution)
   where id = p_incident;

  insert into public.incident_updates (incident_id, author_id, status, body)
  values (p_incident, auth.uid(), 'resolved', btrim(p_resolution));

  perform public.audit_write(
    null, 'incident.resolved', 'incident', p_incident,
    jsonb_build_object('reference', r.reference, 'before', r.status, 'after', 'resolved'),
    'notice', 'platform_only');
end;
$$;

revoke all on function public.resolve_incident(uuid, text) from public, anon;
grant execute on function public.resolve_incident(uuid, text) to authenticated;

-- ---------- Row level security -----------------------------------------
alter table public.incidents enable row level security;
alter table public.incident_updates enable row level security;

drop policy if exists incidents_select on public.incidents;
create policy incidents_select
  on public.incidents for select
  using (public.is_platform_admin());

drop policy if exists incident_updates_select on public.incident_updates;
create policy incident_updates_select
  on public.incident_updates for select
  using (public.is_platform_admin());

-- Every write goes through the functions above, which is what keeps the
-- reference number unique, the resolution note mandatory and the audit row
-- written.
revoke insert, update, delete on public.incidents from anon, authenticated;
revoke insert, update, delete on public.incident_updates from anon, authenticated;
